# NUMerical PYthon

In [ ]:
import numpy as np
a=np.array([1,2,3])
print(a)

In [ ]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,])
print(a)

In [12]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8])
print(a[1:5])
print(a)

[2 3 4 5]
[1 2 3 4 5 6 7 8]


In [17]:
import numpy as np
b=np.array([1,2,3,4,5,6,7,8])
print(b)
b=b[0:5]
print(b[0:3])
print(b)

[1 2 3 4 5 6 7 8]
[1 2 3]
[1 2 3 4 5]


In [15]:
print(b.dtype)

int64


# Indexing Array

In [18]:
import numpy as np
a=np.array([1,2,3,4,5,6])
print(a[2])

3


In [22]:
n=np.arange(0,20,2)
print(n)

[ 0  2  4  6  8 10 12 14 16 18]


# Copy & view


In [30]:
import numpy as np
a=np.array([1,2,3,4,5,6])
x=a.view() #view - copy and update if original or current arr update - interlinked
k=a.copy() #copy copy as it is - not update even original arr update 
a[2]=10
print("updated ",a)
print("copied ",x) 
print("view ",k)


updated  [ 1  2 10  4  5  6]
copied  [ 1  2 10  4  5  6]
view  [1 2 3 4 5 6]


# Fancy Indexing

# add

In [32]:
i=np.array([1,2,3,4])
j=np.array([5,6,7,8])
res=np.add(i,j)
print(res)

[ 6  8 10 12]


# numpy Broadcasting

In [38]:
i=np.array([1,2,3,4])
j=np.array([[5],[6],[7],[8]])
res=i+j
print(res)

[[ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]]


# Scholar

In [40]:
i=np.array([1,2,3,4])
j=5  #scholar - add a num  to individual ele to arr
res=i+j
print(res)

[6 7 8 9]


In [52]:
l=np.arange(1,11)
m=input("enter num table :")
n=l*m
print(n)

enter num table : 2


UFuncTypeError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('int64'), dtype('<U1')) -> None